/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package kalkulator;

import javafx.application.Application;
import javafx.geometry.Pos;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.control.TextField;
import javafx.scene.image.ImageView;
import javafx.scene.layout.StackPane;
import javafx.scene.layout.VBox;
import javafx.scene.text.Text;
import javafx.stage.Stage;

public class App extends Application {
    private Stage stage;

    @Override
    public void start(Stage mainStage) {
        //handling stage
        stage = mainStage;

        //stage
        stage.setTitle("Tugas Praktikum 9");
        stage.setScene(getScene1());
        stage.show();
    }

    private Scene getScene1() {

        Text tTitle = new Text("Kalkulator Sehat");
        Button bMulai = new Button("Mulai");
        VBox sectionRight = new VBox(tTitle, bMulai);
        sectionRight.setSpacing(50);
        sectionRight.setAlignment(Pos.CENTER);
        sectionRight.setPrefWidth(30);

        //Action untuk Button

        bMulai.setOnAction(v -> {
            stage.setScene(getScene2());
        });

        //section
        ImageView ivBanner = new ImageView("/images/123.png");
        ivBanner.setFitWidth(260);
        ivBanner.setFitHeight(300);
        ivBanner.setPreserveRatio(true);

        //rootNode
        VBox rootNode = new VBox(ivBanner, sectionRight);
        rootNode.setAlignment(Pos.CENTER);

        Scene scene = new Scene(new StackPane(rootNode), 640, 480);

        //atur css
         scene.getStylesheets().add(getClass().getResource("/styles/style.css").toExternalForm());
        return scene;
    }

    private Scene getScene2() {
        Text tTitle = new Text("PILIH MENU");
        Button bKalkulator1 = new Button("Body Mass Index (BMI)");
        Button bKalkulator2 = new Button("Berat Badan Ideal Pria");
        Button bKalkulator3 = new Button("Berat Badan Ideal Wanita");
        VBox sectionRight = new VBox(tTitle, bKalkulator1, bKalkulator2, bKalkulator3);
        sectionRight.setSpacing(15);
        sectionRight.setAlignment(Pos.TOP_CENTER);
        sectionRight.setPrefWidth(0);

        //Action untuk Button

        bKalkulator1.setOnAction(v -> {
            stage.setScene(getScene3("Body Mass Index (BMI)", false));
        });

        bKalkulator2.setOnAction(v -> {
            stage.setScene(getScene3("Berat Badan Ideal Pria", true));
        });

        bKalkulator3.setOnAction(v -> {
            stage.setScene(getScene3("Berat Badan Ideal Wanita", true));
        });

        //rootNode
        VBox rootNode = new VBox(sectionRight);

        Scene scene = new Scene(new StackPane(rootNode), 640, 480);

        //Atur css
        scene.getStylesheets().add(getClass().getResource("/styles/style.css").toExternalForm());
        return scene;

    }
    
    
    
    private Scene getScene3(String kalkulator, boolean tinggiBadan) {
        Text tTitle = new Text("Jenis Kalkulator : " + kalkulator);
        Label lInput1 = new Label("Tinggi Badan(CM)");
        TextField tInput1 = new TextField("0");
        tInput1.setPromptText("CM");
        Label lInput2 = new Label("Berat Badan(KG)");
        TextField tInput2 = new TextField("0");
        Label lHasil = new Label();

        Button bClear = new Button("Clear");
        Button bCalculate = new Button("Calculate");
        Button bBackToHome = new Button("BACK TO HOME");

        VBox sectionRight;

        if (tinggiBadan) {
            sectionRight = new VBox(tTitle, lInput1, tInput1, lHasil, bClear, bCalculate, bBackToHome);

        } else {
            sectionRight = new VBox(tTitle, lInput1, tInput1, lInput2, tInput2, lHasil, bClear, bCalculate,
                    bBackToHome);
        }
        sectionRight.setSpacing(15);
        sectionRight.setAlignment(Pos.TOP_CENTER);
        sectionRight.setPrefWidth(0);

        //Action untuk Button
        bClear.setOnAction(v -> {
            tInput1.setText("0");
            tInput2.setText("0");
        });

         bCalculate.setOnAction(v -> {
            try {
                double tinggi1 = Double.parseDouble(tInput1.getText());
                double tinggi2 = Double.parseDouble(tInput1.getText());
                double berat = Double.parseDouble(tInput2.getText());
                double hasil = 0;
                tinggi1 /= 100;

                if (!tinggiBadan) {
                    // Menghitung Body Mass Index (BMI)
                    hasil = berat / (tinggi1 * tinggi1);
                } else {
                    // Menghitung berat badan ideal (pria atau wanita)
                    if (kalkulator.equals("Berat Badan Ideal Pria")) {
                        hasil = (tinggi2 - 100) - ((tinggi2 - 100) * 0.1);
                    } else if (kalkulator.equals("Berat Badan Ideal Wanita")) {
                        hasil = (tinggi2 - 100) - ((tinggi2 - 100) * 0.15);
                    }
                }
                
                // Menambahkan keterangan berdasarkan hasil
                String keterangan = "";
                if (hasil < 18.5) {
                    keterangan = "Berat badan kurang atau kekurangan berat badan";
                } else if (hasil >= 18.5 && hasil <= 24.9) {
                    keterangan = "Berat badan normal atau sehat";
                } else if (hasil >= 25.0 && hasil <= 29.9) {
                    keterangan = "Berat badan berlebih atau overweight";
                } else if (hasil >= 30.0) {
                    keterangan = "Obesitas";
                }

                //menampilkan hasil 
                if (tinggiBadan) {
                    lHasil.setText("Hasil: " + hasil + " kg");
                } else {
                    lHasil.setText("Hasil: " + hasil + "\nKeterangan : " + keterangan);
                    }

             } catch (NumberFormatException e) {
                 lHasil.setText("Input tidak Valid");
                System.out.println("e:"+e);
            
            }
        });

        bBackToHome.setOnAction(v -> {
            stage.setScene(getScene2());
        });

        //rootNode
        VBox rootNode = new VBox(sectionRight);

        Scene scene = new Scene(new StackPane(rootNode), 640, 480);

        //atur css
        scene.getStylesheets().add(getClass().getResource("/styles/style.css").toExternalForm());
        return scene;

    }
    
    public static void main(String[] args) {
        launch();
    }

}