/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package kalkulator;

import javafx.application.Application;
import javafx.geometry.Pos;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.control.TextField;
import javafx.scene.image.Image;
import javafx.scene.image.ImageView;
import javafx.scene.layout.HBox;
import javafx.scene.layout.VBox;
import javafx.scene.text.Font;
import javafx.stage.Stage;

public class App extends Application {
    private Stage stage;

    @Override
    public void start(Stage primaryStage) {
        primaryStage.setTitle("H071221013");    
        stage = primaryStage;  
        getScene1();
        stage.show();   //untuk menampilkan jendela aplikasi setelah semua selesai dilakukan
    }

    public void getScene1() {   
        Image image = new Image("/kall.jpg");
        ImageView imageView = new ImageView(image); 

        Label label = new Label("KALKULATOR SEDERHANA");   
        label.setFont(Font.font("Gill Sans MT", 14));  

        Button button1 = new Button("Mulai");
        button1.getStyleClass().add("custom-button1");
        button1.setOnAction(action -> { //ketika tombol di klik, mengubah tampilan ke scene2
            getScene2();
        });

        VBox vBox = new VBox(imageView, label, button1);    
        vBox.setAlignment(Pos.CENTER);  
        vBox.setSpacing(15); 
        vBox.getStyleClass().add("scene1-vbox");
        Scene scene1 = new Scene(vBox, 300, 480);   
        scene1.getStylesheets().add(getClass().getResource("/style.css").toExternalForm()); 
        stage.setScene(scene1); 
    }

    public void getScene2() {
        Label label = new Label("Pilih Menu");
        label.setFont(Font.font("Gill Sans MT", 25));

        Button button2 = new Button("Aritmatika Sederhana");
        button2.getStyleClass().add("custom-button1");
        button2.setOnAction(action -> {
            showAritmatika();
        });
        
        Button kubus = new Button("Operasi Kubus");
        kubus.getStyleClass().add("custom-button1");
        kubus.setOnAction(action -> {
            showKubus();
        });

        Button balok = new Button("Operasi Balok");
        balok.getStyleClass().add("custom-button1");
        balok.setOnAction(action -> {
            showBalok();
        });

        VBox vBox = new VBox(label, button2, kubus, balok);
        vBox.setAlignment(Pos.CENTER);
        vBox.setSpacing(15);
        vBox.getStyleClass().add("scene2-vbox");
        Scene scene2 = new Scene(vBox, 300, 480);
        scene2.getStylesheets().add(getClass().getResource("/style.css").toExternalForm());  //toEx untuk mndpatkn lokai file css
        stage.setScene(scene2);
    }

    public void showAritmatika() {
        Label label = new Label("Aritmatika Sederhana");
        label.setFont(Font.font("Gill Sans MT", 25));

        TextField input1 = new TextField(); 
        input1.setPromptText("Input angka");
        TextField input2 = new TextField();
        input2.setPromptText("Input angka");
        Label output = new Label(); //menampilkan hasil

        Button tambah = new Button("+");
        tambah.getStyleClass().add("custom-button3");
        tambah.setOnAction(action -> {  
            try {   //pengecualian
                int angka1 = Integer.parseInt(input1.getText());
                int angka2 = Integer.parseInt(input2.getText());
                int hasil = angka1 + angka2;
                output.setText("Hasil = " + hasil);
            } catch (NumberFormatException e) {
                output.setText("invalid");
            }
        });

        Button kurang = new Button("-");
        kurang.getStyleClass().add("custom-button3");
        kurang.setOnAction(action -> {
            try {
                int angka1 = Integer.parseInt(input1.getText());
                int angka2 = Integer.parseInt(input2.getText());
                int hasil = angka1 - angka2;
                output.setText("Hasil = " + hasil);
            } catch (NumberFormatException e) {
                output.setText("invalid");
            }
        });

        HBox tambahKurang = new HBox(tambah, kurang);
        tambahKurang.setAlignment(Pos.CENTER);
        tambahKurang.setSpacing(10);

        Button kali = new Button("x");
        kali.getStyleClass().add("custom-button3");
        kali.setOnAction(action -> {
            try {
                int angka1 = Integer.parseInt(input1.getText());
                int angka2 = Integer.parseInt(input2.getText());
                int hasil = angka1 * angka2;
                output.setText("Hasil = " + hasil);
            } catch (NumberFormatException e) {
                output.setText("invalid");
            }
        });

        Button bagi = new Button("/");
        bagi.getStyleClass().add("custom-button3");
        bagi.setOnAction(action -> {
            try {
                int angka1 = Integer.parseInt(input1.getText());
                int angka2 = Integer.parseInt(input2.getText());
                Double hasil = (double) angka1 / angka2;
                output.setText("Hasil = " + hasil);
            } catch (NumberFormatException e) {
                output.setText("invalid");
            }
        });

        HBox kaliBagi = new HBox(kali, bagi);
        kaliBagi.setAlignment(Pos.CENTER);
        kaliBagi.setSpacing(10);

        VBox tambahKurangKaliBagi = new VBox(tambahKurang, kaliBagi);
        tambahKurangKaliBagi.setSpacing(10);

        Button clear = new Button("Clear"); //menghapus isi dari input 1 2
        clear.getStyleClass().add("custom-button1");
        clear.setOnAction(action -> {
            input1.setText(""); //isi ip1&2 dan teksnya menjadi String kosong
            input2.setText("");
        });

        Button back = new Button("Kembali");    //untuk kembali ke tmpilan sblumnya
        back.getStyleClass().add("custom-button2");
        back.setOnAction(action -> {
            getScene2();
        });

        VBox vBox = new VBox(label, input1, input2, output, tambahKurangKaliBagi, clear, back);
        vBox.setAlignment(Pos.CENTER);
        vBox.setSpacing(15);
        vBox.getStyleClass().add("scene3-vbox");
        Scene scene3 = new Scene(vBox, 300, 520);
        scene3.getStylesheets().add(getClass().getResource("/style.css").toExternalForm());
        stage.setScene(scene3);
    }

    public void showKubus() {
        Label label = new Label("Operasi Kubus");
        label.setFont(Font.font("Gill Sans MT", 25));

        Label label2 = new Label("Masukkan panjang rusuk :");
        TextField input = new TextField();
        Label output = new Label();

        Button keliling = new Button("Keliling");
        keliling.getStyleClass().add("custom-button3");
        keliling.setOnAction(action -> {
            try {
                int angka = Integer.parseInt(input.getText());
                int hasil = 12 * angka;
                output.setText("Hasil = " + hasil);
            } catch (NumberFormatException e) {
                output.setText("invalid");
            }
        });

        Button luas = new Button("Luas");
        luas.getStyleClass().add("custom-button3");
        luas.setOnAction(action -> {
            try {
                int angka = Integer.parseInt(input.getText());
                int hasil = 6 * (angka*angka);
                output.setText("Hasil = " + hasil);
            } catch (NumberFormatException e) {
                output.setText("invalid");
            }
        });

        HBox luke = new HBox(keliling, luas);
        luke.setAlignment(Pos.CENTER);
        luke.setSpacing(5);

        Button volume = new Button("Volume");
        volume.getStyleClass().add("custom-button4");
        volume.setOnAction(action -> {
            try {
                int angka = Integer.parseInt(input.getText());
                int hasil = angka*angka*angka;
                output.setText("Hasil = " + hasil);
            } catch (NumberFormatException e) {
                output.setText("invalid");
            }
        });

        VBox lukevo = new VBox(luke, volume);
        lukevo.setAlignment(Pos.CENTER);
        lukevo.setSpacing(5);

        Button clear = new Button("Clear");
        clear.getStyleClass().add("custom-button1");
        clear.setOnAction(action -> {
            input.setText("");
        });

        Button back = new Button("Kembali");
        back.getStyleClass().add("custom-button2");
        back.setOnAction(action -> {
            getScene2();
        });

        VBox vBox = new VBox(label, label2, input, output, lukevo, clear, back);
        vBox.setAlignment(Pos.CENTER);
        vBox.setSpacing(15);
        Scene scene3 = new Scene(vBox, 300, 520);
        scene3.getStylesheets().add(getClass().getResource("/style.css").toExternalForm());
        stage.setScene(scene3);
    }

    public void showBalok() {
        Label label = new Label("Operasi Balok");
        label.setFont(Font.font("Gill Sans MT", 25));

        Label label2 = new Label("Masukkan panjang :");
        TextField input1 = new TextField();
        Label label3 = new Label("Masukkan lebar :");
        TextField input2 = new TextField();
        Label label4 = new Label("Masukkan tinggi :");
        TextField input3 = new TextField();
        Label output = new Label();

        Button keliling = new Button("Keliling");
        keliling.getStyleClass().add("custom-button3");
        keliling.setOnAction(action -> {
            try {
                int angka1 = Integer.parseInt(input1.getText());    //akses nilai input jika bertipe int
                int angka2 = Integer.parseInt(input2.getText());
                int angka3 = Integer.parseInt(input3.getText());
                int hasil = 4 * (angka1 + angka2 + angka3);
                output.setText("Hasil = " + hasil);
            } catch (NumberFormatException e) {
                output.setText("invalid");
            }
        });

        Button luas = new Button("Luas");
        luas.getStyleClass().add("custom-button3");
        luas.setOnAction(action -> {
            try {
                int angka1 = Integer.parseInt(input1.getText());
                int angka2 = Integer.parseInt(input2.getText());
                int angka3 = Integer.parseInt(input3.getText());
                int hasil = 2 * (angka1 * angka2 + angka1 * angka3 + angka2 * angka3);
                output.setText("Hasil = " + hasil);
            } catch (NumberFormatException e) {
                output.setText("Bukan integer");
            }
        });

        HBox luke = new HBox(keliling, luas);
        luke.setAlignment(Pos.CENTER);
        luke.setSpacing(5);

        Button volume = new Button("Volume");
        volume.getStyleClass().add("custom-button4");
        volume.setOnAction(action -> {
            try {
                int angka1 = Integer.parseInt(input1.getText());
                int angka2 = Integer.parseInt(input2.getText());
                int angka3 = Integer.parseInt(input3.getText());
                int hasil = angka1*angka2*angka3;
                output.setText("Hasil = " + hasil);
            } catch (NumberFormatException e) {
                output.setText("Bukan integer");
            }
        });

        VBox lukevo = new VBox(luke, volume);
        lukevo.setAlignment(Pos.CENTER);
        lukevo.setSpacing(5);

        Button clear = new Button("Clear");
        clear.getStyleClass().add("custom-button1");
        clear.setOnAction(action -> {
            input1.setText("");
            input2.setText("");
            input3.setText("");
        });

        Button back = new Button("Kembali");
        back.getStyleClass().add("custom-button2");
        back.setOnAction(action -> {
            getScene2();
        });

        VBox vBox = new VBox(label, label2, input1, label3, input2, label4, input3, output, lukevo, clear, back);
        vBox.setAlignment(Pos.CENTER);
        vBox.setSpacing(5);
        vBox.getStyleClass().add("scene4-vbox");
        Scene scene3 = new Scene(vBox, 300, 520);
        scene3.getStylesheets().add(getClass().getResource("/style.css").toExternalForm());
        stage.setScene(scene3);
    }

    public static void main(String[] args) {
        Application.launch(args);
    }
}