//  * This Java source file was generated by the Gradle 'init' task.
//  */
package calculate;

import javax.swing.Action;
import javafx.application.Application;
import javafx.stage.Stage;
import javafx.scene.Scene;
import javafx.scene.Group;
import javafx.scene.control.Button;
import javafx.scene.control.ComboBox;
import javafx.scene.control.Label;
import javafx.scene.control.TextField;
import javafx.scene.image.Image;
import javafx.scene.image.ImageView;
import javafx.scene.layout.AnchorPane;
import javafx.scene.layout.HBox;
import javafx.scene.layout.VBox;
import javafx.scene.paint.Color;
import javafx.scene.text.Font;
import javafx.geometry.Pos;
import javafx.scene.layout.Background;
import javafx.scene.layout.BackgroundFill;
import javafx.scene.layout.BorderPane;
import javafx.scene.layout.CornerRadii;

public class App extends Application {
    private Stage stage;
    Label hasiLabel;

    BackgroundFill backgroundFill = new BackgroundFill(Color.BLACK, new CornerRadii(5), null);
    Background background = new Background(backgroundFill);

    BackgroundFill backgroundFill1 = new BackgroundFill(Color.BLUE, new CornerRadii(5), null);
    Background background1 = new Background(backgroundFill1);

    BackgroundFill backgroundFill2 = new BackgroundFill(Color.GREEN, new CornerRadii(5), null);
    Background background2 = new Background(backgroundFill2);

    @Override
    public void start(Stage primaryStage) {
        stage = primaryStage;
        stage.setTitle("Calculate");
        firstScene();
        stage.show();

    }

    private void firstScene() {
        Label label = new Label("MathCalc");
        label.setFont(Font.font("Times New Roman", 20));
        Button button = new Button("Start");
        button.setBackground(background);
        button.setPrefHeight(10);
        button.setPrefWidth(75);
        button.setStyle("-fx-font-size: 15px; -fx-text-fill: white;");
        button.setOnAction(action -> secondScene());
        Image logoImage = new Image("unnamed.png");
        ImageView logoImageView = new ImageView(logoImage);
        logoImageView.setFitWidth(200);
        logoImageView.setFitHeight(300);
        VBox vBox = new VBox(10, logoImageView, label, button);
        vBox.setAlignment(Pos.CENTER);
        vBox.setStyle("-fx-background-color: #00BFFF;");
        Scene sc = new Scene(vBox, 600, 600);
        stage.setScene(sc);
    }

    private void secondScene() {
        Label label1 = new Label("Pilihan");
        label1.setStyle("-fx-font-size: 30px; -fx-text-fill: black;");
        Button button1 = new Button("Bangun Ruang");
        button1.setBackground(background1);
        button1.setPrefHeight(50);
        button1.setPrefWidth(300);
        button1.setStyle("-fx-font-size: 24px; -fx-text-fill: white;");
        button1.setOnAction(action -> bangunRuangScene());
        Button button2 = new Button("Bangun Datar");
        button2.setBackground(background1);
        button2.setPrefHeight(50);
        button2.setPrefWidth(300);
        button2.setStyle("-fx-font-size: 24px; -fx-text-fill: white;");
        button2.setOnAction(action -> bangunDatarScene());
        Button trigo = new Button("Trigonometri");
        trigo.setBackground(background1);
        trigo.setPrefHeight(50);
        trigo.setPrefWidth(300);
        trigo.setStyle("-fx-font-size: 24px; -fx-text-fill: white;");
        trigo.setOnAction(action -> trigonometry());
        // Button time = new Button("Kalkulator Waktu");
        // time.setBackground(background1);
        // time.setPrefHeight(50);
        // time.setPrefWidth(300);
        // time.setStyle("-fx-font-size: 24px; -fx-text-fill: white;");
        // time.setOnAction(action -> konversiWaktu());

        VBox menu = new VBox(10, label1);
        menu.setAlignment(Pos.TOP_CENTER);

        VBox vbox = new VBox(10, menu, button1, button2, trigo);
        vbox.setAlignment(Pos.CENTER);
        vbox.setStyle("-fx-background-color: #00BFFF;");
        Scene sc1 = new Scene(vbox, 600, 600);
        stage.setScene(sc1);
    }

    private void bangunRuangScene() {

        Button button3 = new Button("Kubus");
        button3.setBackground(background);
        button3.setPrefHeight(50);
        button3.setPrefWidth(150);
        button3.setStyle("-fx-font-size: 24px; -fx-text-fill: white;");
        Button button4 = new Button("Balok");
        button4.setBackground(background);
        button4.setPrefHeight(50);
        button4.setPrefWidth(150);
        button4.setStyle("-fx-font-size: 24px; -fx-text-fill: white;");
        Button button5 = new Button("Tabung");
        button5.setBackground(background);
        button5.setPrefHeight(50);
        button5.setPrefWidth(150);
        button5.setStyle("-fx-font-size: 24px; -fx-text-fill: white;");
        Button button6 = new Button("Bola");
        button6.setBackground(background);
        button6.setPrefHeight(50);
        button6.setPrefWidth(150);
        button6.setStyle("-fx-font-size: 24px; -fx-text-fill: white;");

        button3.setOnAction(action -> hitungKubus());
        button4.setOnAction(action -> hitungBalok());
        button5.setOnAction(action -> hitungTabung());
        button6.setOnAction(action -> hitungBola());

        Button backhome = new Button("Back to Home");
        backhome.setBackground(background);
        backhome.setPrefHeight(50);
        backhome.setPrefWidth(310);
        backhome.setStyle("-fx-font-size: 24px; -fx-text-fill: white;");
        backhome.setOnAction(action -> secondScene());

        HBox hBoxone = new HBox(10, button3, button4);
        hBoxone.setAlignment(Pos.TOP_CENTER);

        HBox hboxtwo = new HBox(10, button5, button6);
        hboxtwo.setAlignment(Pos.TOP_CENTER);

        VBox hasil = new VBox();
        hasil.setSpacing(10);
        hasil.setAlignment(Pos.CENTER);

        VBox root = new VBox(hBoxone, hboxtwo, hasil, backhome);
        root.setAlignment(Pos.CENTER);
        root.setSpacing(10);
        root.setStyle("-fx-background-color: #00BFFF;");
        Scene sc2 = new Scene(root, 600, 600);
        stage.setScene(sc2);
    }

    private void hitungKubus() {
        Label label1 = new Label();
        Label label2 = new Label();

        Label label = new Label("Masukkan panjang sisi kubus:");
        TextField sisiTextField = new TextField();
        sisiTextField.setMaxWidth(100);
        sisiTextField.setMaxHeight(40);
        sisiTextField.setAlignment(Pos.CENTER);
        Button hitungButton = new Button("Calculate");
        hitungButton.setBackground(background2);
        hitungButton.setStyle("-fx-font-size: 15px; -fx-text-fill: white;");
        hitungButton.setOnAction(action -> {
            try {
                double sisi = Double.parseDouble(sisiTextField.getText());
                double volume = sisi * sisi * sisi;
                label1.setText("Volume kubus: " + String.format("%.2f", volume));
                label1.setBackground(background);
                label1.setPrefWidth(150);
                label1.setPrefHeight(75);
                label1.setAlignment(Pos.CENTER);
                label1.setStyle("-fx-font-size: 15px; -fx-text-fill: white;");

                double luas = sisi * sisi;
                label2.setText("Luas kubus: " + String.format("%.2f", luas));
                label2.setBackground(background);
                label2.setPrefWidth(150);
                label2.setPrefHeight(75);
                label2.setAlignment(Pos.CENTER);
                label2.setStyle("-fx-font-size: 15px; -fx-text-fill: white;");

            } catch (NumberFormatException e) {
                label1.setText("Masukkan angka yang valid");
                label2.setText("Masukkan angka yang valid");
            }
        });
        Button backhome = new Button("Back to Menu");
        backhome.setOnAction(action -> bangunRuangScene());
        VBox vbox = new VBox(10, label, sisiTextField, hitungButton, label1, label2, backhome);
        vbox.setAlignment(Pos.CENTER);
        vbox.setStyle("-fx-background-color: #00BFFF;");

        Scene scene = new Scene(vbox, 600, 600);
        stage.setScene(scene);
    }

    private void hitungBalok() {
        Label label1 = new Label("Masukkan panjang:");
        TextField panjangTextField = new TextField();
        panjangTextField.setMaxWidth(100);
        panjangTextField.setMaxHeight(40);
        Label label2 = new Label("Masukkan lebar:");
        TextField lebarTextField = new TextField();
        lebarTextField.setMaxWidth(100);
        lebarTextField.setMaxHeight(40);
        Label label3 = new Label("Masukkan tinggi:");
        TextField tinggiTextField = new TextField();
        tinggiTextField.setMaxWidth(100);
        tinggiTextField.setMaxHeight(40);
        Button hitungButton = new Button("Calculate");
        hitungButton.setBackground(background2);
        hitungButton.setStyle("-fx-font-size: 15px; -fx-text-fill: white;");

        Label hasilVolume = new Label();
        Label hasilLuas = new Label();

        hitungButton.setOnAction(action -> {
            try {
                Double panjang = Double.parseDouble(panjangTextField.getText());
                Double lebar = Double.parseDouble(lebarTextField.getText());
                Double tinggi = Double.parseDouble(tinggiTextField.getText());
                Double volume = panjang * lebar * tinggi;
                hasilVolume.setText("Volume balok: " + String.format("%.2f", volume));
                hasilVolume.setBackground(background);
                hasilVolume.setPrefWidth(150);
                hasilVolume.setPrefHeight(75);
                hasilVolume.setAlignment(Pos.CENTER);
                hasilVolume.setStyle("-fx-font-size: 15px; -fx-text-fill: white;");

                Double luas = 2 * (panjang * lebar + panjang * tinggi + lebar * tinggi);
                hasilLuas.setText("Luas Balok : " + String.format("%.2f", luas));
                hasilLuas.setBackground(background);
                hasilLuas.setPrefWidth(150);
                hasilLuas.setPrefHeight(75);
                hasilLuas.setAlignment(Pos.CENTER);
                hasilLuas.setStyle("-fx-font-size: 15px; -fx-text-fill: white;");
            } catch (NumberFormatException e) {
                hasilVolume.setText("Masukkan angka yang valid");
                hasilLuas.setText("Masukkan angka yang valid");
            }
        });
        Button backhome = new Button("Back to Menu");
        backhome.setOnAction(action -> bangunRuangScene());

        VBox vbox = new VBox(10, label1, panjangTextField, label2, lebarTextField, label3, tinggiTextField,
                hitungButton, hasilVolume, hasilLuas, backhome);
        vbox.setAlignment(Pos.CENTER);
        vbox.setStyle("-fx-background-color: #00BFFF;");

        Scene scene = new Scene(vbox, 600, 600);
        stage.setScene(scene);
    }

    private void hitungTabung() {
        final double phi = 3.1415;
        Label label1 = new Label("Masukkan jari-jari:");
        TextField jariJariTextField = new TextField();
        jariJariTextField.setMaxWidth(100);
        jariJariTextField.setMaxHeight(40);
        Label label2 = new Label("Masukkan tinggi:");
        TextField tinggiTextField = new TextField();
        tinggiTextField.setMaxWidth(100);
        tinggiTextField.setMaxHeight(40);
        Button hitungButton = new Button("Calculate");
        hitungButton.setBackground(background2);
        hitungButton.setStyle("-fx-font-size: 15px; -fx-text-fill: white;");

        Label hasilVolume = new Label();
        Label hasilLuas = new Label();

        hitungButton.setOnAction(action -> {
            try {
                double jariJari = Double.parseDouble(jariJariTextField.getText());
                double tinggi = Double.parseDouble(tinggiTextField.getText());
                double volume = Math.PI * Math.pow(jariJari, 2) * tinggi;
                hasilVolume.setText("Volume tabung: " + String.format("%.2f", volume));
                hasilVolume.setBackground(background);
                hasilVolume.setPrefWidth(150);
                hasilVolume.setPrefHeight(75);
                hasilVolume.setAlignment(Pos.CENTER);
                hasilVolume.setStyle("-fx-font-size: 15px; -fx-text-fill: white;");

                double luas = 2 * phi * jariJari * (jariJari + tinggi);
                hasilLuas.setText("Hasil Luas : " + String.format("%.2f", luas));
                hasilLuas.setBackground(background);
                hasilLuas.setPrefWidth(150);
                hasilLuas.setPrefHeight(75);
                hasilLuas.setAlignment(Pos.CENTER);
                hasilLuas.setStyle("-fx-font-size: 15px; -fx-text-fill: white;");
            } catch (NumberFormatException e) {
                hasilVolume.setText("Masukkan angka yang valid");
                hasilLuas.setText("Masukkan angka yang valid");
            }
        });
        Button backhome = new Button("Back to Menu");
        backhome.setOnAction(action -> bangunRuangScene());

        VBox vbox = new VBox(10, label1, jariJariTextField, label2, tinggiTextField, hitungButton, hasilVolume,
                hasilLuas, backhome);
        vbox.setAlignment(Pos.CENTER);
        vbox.setStyle("-fx-background-color: #00BFFF;");

        Scene scene = new Scene(vbox, 600, 600);
        stage.setScene(scene);
    }

    private void hitungBola() {
        final double phi = 3.1415;
        Label label = new Label("Masukkan jari-jari bola:");
        TextField jariJariTextField = new TextField();
        jariJariTextField.setMaxWidth(100);
        jariJariTextField.setMaxHeight(40);
        Button hitungButton = new Button("Calculate");
        hitungButton.setBackground(background2);
        hitungButton.setStyle("-fx-font-size: 15px; -fx-text-fill: white;");

        Label hasilVolume = new Label();
        Label hasilLuas = new Label();
        hitungButton.setOnAction(action -> {
            try {
                double jariJari = Double.parseDouble(jariJariTextField.getText());
                double volume = (4.0 / 3.0) * Math.PI * Math.pow(jariJari, 3);
                hasilVolume.setText("Volume bola: " + String.format("%.2f", volume));
                hasilVolume.setBackground(background);
                hasilVolume.setPrefWidth(150);
                hasilVolume.setPrefHeight(75);
                hasilVolume.setAlignment(Pos.CENTER);
                hasilVolume.setStyle("-fx-font-size: 15px; -fx-text-fill: white;");

                double luas = 4 * phi * jariJari * jariJari;
                hasilLuas.setText("Luas Bola : " + String.format("%.2f", luas));
                hasilLuas.setBackground(background);
                hasilLuas.setPrefWidth(150);
                hasilLuas.setPrefHeight(75);
                hasilLuas.setAlignment(Pos.CENTER);
                hasilLuas.setStyle("-fx-font-size: 15px; -fx-text-fill: white;");
            } catch (NumberFormatException e) {
                hasilVolume.setText("Masukkan angka yang valid");
                hasilLuas.setText("Masukkan angka yang valid");
            }
        });
        Button backhome = new Button("Back to Menu");
        backhome.setOnAction(action -> bangunRuangScene());

        VBox vbox = new VBox(10, label, jariJariTextField, hitungButton, hasilVolume, hasilLuas, backhome);
        vbox.setAlignment(Pos.CENTER);
        vbox.setStyle("-fx-background-color: #00BFFF;");

        Scene scene = new Scene(vbox, 600, 600);
        stage.setScene(scene);
    }

    private void bangunDatarScene() {
        Button button7 = new Button("Persegi");
        button7.setBackground(background);
        button7.setPrefHeight(50);
        button7.setPrefWidth(150);
        button7.setStyle("-fx-font-size: 24px; -fx-text-fill: white;");
        Button button8 = new Button("Segi Tiga");
        button8.setBackground(background);
        button8.setPrefHeight(50);
        button8.setPrefWidth(150);
        button8.setStyle("-fx-font-size: 24px; -fx-text-fill: white;");
        Button button9 = new Button("Lingkaran");
        button9.setBackground(background);
        button9.setPrefHeight(50);
        button9.setPrefWidth(150);
        button9.setStyle("-fx-font-size: 24px; -fx-text-fill: white;");
        Button button10 = new Button("Layang-Layang");
        button10.setBackground(background);
        button10.setPrefHeight(50);
        button10.setPrefWidth(150);
        button10.setStyle("-fx-font-size: 15px; -fx-text-fill: white;");

        button7.setOnAction(action -> hitungPersegi());
        button8.setOnAction(action -> hitungSegitiga());
        button9.setOnAction(action -> hitungLingkaran());
        button10.setOnAction(action -> hitungLayangLayang());

        HBox hBox1 = new HBox(10, button7, button8);
        hBox1.setAlignment(Pos.TOP_CENTER);

        HBox hbox2 = new HBox(10, button9, button10);
        hbox2.setAlignment(Pos.TOP_CENTER);

        Button backhome = new Button("Back to Menu");
        backhome.setBackground(background);
        backhome.setPrefHeight(50);
        backhome.setPrefWidth(310);
        backhome.setStyle("-fx-font-size: 24px; -fx-text-fill: white;");

        backhome.setOnAction(action -> secondScene());
        VBox hasil = new VBox();
        hasil.setSpacing(10);
        hasil.setAlignment(Pos.CENTER);

        VBox root = new VBox(hBox1, hbox2, hasil, backhome);
        root.setAlignment(Pos.CENTER);
        root.setSpacing(10);
        root.setStyle("-fx-background-color: #00BFFF;");

        Scene sc3 = new Scene(root, 600, 600);
        stage.setScene(sc3);

    }

    private void hitungPersegi() {
        Label kelilingPersegi = new Label();
        Label luasPersegi = new Label();

        Label label = new Label("Masukkan sisi Persegi:");
        TextField sisiTextField = new TextField();
        sisiTextField.setMaxWidth(100);
        sisiTextField.setMaxHeight(40);
        Button hitungButton = new Button("Calculate");
        hitungButton.setBackground(background2);
        hitungButton.setStyle("-fx-font-size: 15px; -fx-text-fill: white;");

        hitungButton.setOnAction(action -> {
            try {
                double sisi = Double.parseDouble(sisiTextField.getText());
                double keliling = 4 * sisi;
                kelilingPersegi.setText("Keliling : " + String.format("%.2f", keliling));
                kelilingPersegi.setBackground(background);
                kelilingPersegi.setPrefWidth(150);
                kelilingPersegi.setPrefHeight(75);
                kelilingPersegi.setAlignment(Pos.CENTER);
                kelilingPersegi.setStyle("-fx-font-size: 15px; -fx-text-fill: white;");

                double luas = sisi * sisi;
                luasPersegi.setText("Luas : " + String.format("%.2f", luas));
                luasPersegi.setBackground(background);
                luasPersegi.setPrefWidth(150);
                luasPersegi.setPrefHeight(75);
                luasPersegi.setAlignment(Pos.CENTER);
                luasPersegi.setStyle("-fx-font-size: 15px; -fx-text-fill: white;");

            } catch (NumberFormatException e) {
                kelilingPersegi.setText("Masukkan angka yang valid");
                luasPersegi.setText("Masukkan angka yang valid");
            }
        });
        Button backhome = new Button("Back to Menu");
        backhome.setOnAction(action -> bangunDatarScene());

        VBox vbox = new VBox(10, label, sisiTextField, hitungButton, kelilingPersegi, luasPersegi, backhome);
        vbox.setAlignment(Pos.CENTER);
        vbox.setStyle("-fx-background-color: #00BFFF;");

        Scene scene = new Scene(vbox, 600, 600);
        stage.setScene(scene);
    }

    private void hitungSegitiga() {
        Label label1 = new Label("Masukkan alas:");
        TextField alasTextField = new TextField();
        alasTextField.setMaxWidth(100);
        alasTextField.setMaxHeight(40);
        Label label2 = new Label("Masukkan tinggi:");
        TextField tinggiTextField = new TextField();
        tinggiTextField.setMaxWidth(100);
        tinggiTextField.setMaxHeight(40);
        Label label3 = new Label("Masukkan sisi : ");
        TextField sisiTextField = new TextField();
        sisiTextField.setMaxWidth(100);
        sisiTextField.setMaxHeight(40);
        Button hitungButton = new Button("Calculate");
        hitungButton.setBackground(background2);
        hitungButton.setStyle("-fx-font-size: 15px; -fx-text-fill: white;");

        Label kelilingSegitiga = new Label();
        Label luasSegitiga = new Label();
        hitungButton.setOnAction(action -> {
            try {
                double alas = Double.parseDouble(alasTextField.getText());
                double tinggi = Double.parseDouble(tinggiTextField.getText());
                double sisi = Double.parseDouble(sisiTextField.getText());
                double keliling = 3 * sisi;
                kelilingSegitiga.setText("Keliling : " + String.format("%.2f", keliling));
                kelilingSegitiga.setBackground(background);
                kelilingSegitiga.setPrefWidth(150);
                kelilingSegitiga.setPrefHeight(75);
                kelilingSegitiga.setAlignment(Pos.CENTER);
                kelilingSegitiga.setStyle("-fx-font-size: 15px; -fx-text-fill: white;");

                double luas = 0.5 * alas * tinggi;
                luasSegitiga.setText("Luas : " + String.format("%.2f", luas));
                kelilingSegitiga.setBackground(background);
                kelilingSegitiga.setPrefWidth(150);
                kelilingSegitiga.setPrefHeight(75);
                kelilingSegitiga.setAlignment(Pos.CENTER);
                kelilingSegitiga.setStyle("-fx-font-size: 15px; -fx-text-fill: white;");

            } catch (NumberFormatException e) {
                kelilingSegitiga.setText("Masukkan angka yang valid");
                luasSegitiga.setText("Masukkan angka yang valid");
            }
        });
        Button backhome = new Button("Back to Menu");
        backhome.setOnAction(action -> bangunDatarScene());

        VBox vbox = new VBox(10, label1, alasTextField, label2, tinggiTextField, label3, sisiTextField, hitungButton, kelilingSegitiga,
                luasSegitiga, backhome);
        vbox.setAlignment(Pos.CENTER);
        vbox.setStyle("-fx-background-color: #00BFFF;");

        Scene scene = new Scene(vbox, 600, 600);
        stage.setScene(scene);
    }

    private void hitungLingkaran() {
        final double phi = 3.1415;
        Label kelilingLingkaran = new Label();
        Label luasLingkaran = new Label();

        Label label = new Label("Masukkan jari-jari:");
        TextField jariJariTextField = new TextField();
        jariJariTextField.setMaxWidth(100);
        jariJariTextField.setMaxHeight(40);
        Button hitungButton = new Button("Calculate");
        hitungButton.setBackground(background2);
        hitungButton.setStyle("-fx-font-size: 15px; -fx-text-fill: white;");

        hitungButton.setOnAction(action -> {
            try {
                double jariJari = Double.parseDouble(jariJariTextField.getText());
                double keliling = phi * 2 * jariJari;
                kelilingLingkaran.setText("Keliling : " + String.format("%.2f", keliling));
                kelilingLingkaran.setBackground(background);
                kelilingLingkaran.setPrefWidth(150);
                kelilingLingkaran.setPrefHeight(75);
                kelilingLingkaran.setAlignment(Pos.CENTER);
                kelilingLingkaran.setStyle("-fx-font-size: 15px; -fx-text-fill: white;");

                double luas = Math.PI * Math.pow(jariJari, 2);
                luasLingkaran.setText("Luas lingkaran: " + String.format("%.2f", luas));
                luasLingkaran.setBackground(background);
                luasLingkaran.setPrefWidth(150);
                luasLingkaran.setPrefHeight(75);
                luasLingkaran.setAlignment(Pos.CENTER);
                luasLingkaran.setStyle("-fx-font-size: 15px; -fx-text-fill: white;");
            } catch (NumberFormatException e) {
                kelilingLingkaran.setText("Masukkan angka yang valid");
                luasLingkaran.setText("Masukkan angka yang valid");
            }
        });
        Button backhome = new Button("Back to Menu");
        backhome.setOnAction(action -> bangunDatarScene());

        VBox vbox = new VBox(10, label, jariJariTextField, hitungButton, kelilingLingkaran, luasLingkaran, backhome);
        vbox.setAlignment(Pos.CENTER);
        vbox.setStyle("-fx-background-color: #00BFFF;");

        Scene scene = new Scene(vbox, 600, 600);
        stage.setScene(scene);
    }

    private void hitungLayangLayang() {
        Label kelilingLayanglayang = new Label();
        Label luasLayanglayang = new Label();

        Label label1 = new Label("Masukkan diagonal 1:");
        TextField diagonal1TextField = new TextField();
        diagonal1TextField.setMaxWidth(100);
        diagonal1TextField.setMaxHeight(40);
        Label label2 = new Label("Masukkan diagonal 2:");
        TextField diagonal2TextField = new TextField();
        diagonal2TextField.setMaxWidth(100);
        diagonal2TextField.setMaxHeight(40);
        Button hitungButton = new Button("Calculate");
        hitungButton.setBackground(background2);
        hitungButton.setStyle("-fx-font-size: 15px; -fx-text-fill: white;");

        hitungButton.setOnAction(action -> {
            try {
                double diagonal1 = Double.parseDouble(diagonal1TextField.getText());
                double diagonal2 = Double.parseDouble(diagonal2TextField.getText());
                double keliling = 0.5 * diagonal1 * diagonal2;
                kelilingLayanglayang.setText("Keliling : " + String.format("%.2f", keliling));
                kelilingLayanglayang.setBackground(background);
                kelilingLayanglayang.setPrefWidth(150);
                kelilingLayanglayang.setPrefHeight(75);
                kelilingLayanglayang.setAlignment(Pos.CENTER);
                kelilingLayanglayang.setStyle("-fx-font-size: 15px; -fx-text-fill: white;");

                double luas = 0.5 * diagonal1 * diagonal2;
                luasLayanglayang.setText("Luas layang-layang: " + String.format("%.2f", luas));
                luasLayanglayang.setBackground(background);
                luasLayanglayang.setPrefWidth(150);
                luasLayanglayang.setPrefHeight(75);
                luasLayanglayang.setAlignment(Pos.CENTER);
                luasLayanglayang.setStyle("-fx-font-size: 15px; -fx-text-fill: white;");
            } catch (NumberFormatException e) {
                kelilingLayanglayang.setText("Masukkan angka yang valid");
                luasLayanglayang.setText("Masukkan angka yang valid");
            }
        });
        Button backhome = new Button("Back to Menu");
        backhome.setOnAction(action -> bangunDatarScene());

        VBox vbox = new VBox(10, label1, diagonal1TextField, label2, diagonal2TextField, hitungButton,
                kelilingLayanglayang, luasLayanglayang, backhome);
        vbox.setAlignment(Pos.CENTER);
        vbox.setStyle("-fx-background-color: #00BFFF;");

        Scene scene = new Scene(vbox, 600, 600);
        stage.setScene(scene);
    }

    private void trigonometry() {
        Label gino = new Label("Trigonometry");
        gino.setStyle("-fx-font-size: 30px; -fx-text-fill: black;");

        VBox vbox3 = new VBox(10, gino);
        vbox3.setAlignment(Pos.CENTER);

        Label sinLabel = new Label();
        Label cosLabel = new Label();
        Label tanLabel = new Label();
        TextField inputTextField = new TextField();
        inputTextField.setMaxWidth(100);
        inputTextField.setMaxHeight(40);
        inputTextField.setPromptText("Masukkan Inputan");
        Button hitungbutton = new Button("Calculate");
        hitungbutton.setBackground(background2);
        hitungbutton.setStyle("-fx-font-size: 15px; -fx-text-fill: white;");

        hitungbutton.setOnAction(action -> {
            try {
                double angle = Double.parseDouble(inputTextField.getText());
                double radians = Math.toRadians(angle);

                double sin = Math.sin(radians);
                double cos = Math.cos(radians);
                double tan = Math.tan(radians);

                sinLabel.setText("Sinus   : " + String.format("%.2f", sin));
                sinLabel.setBackground(background);
                sinLabel.setPrefWidth(150);
                sinLabel.setPrefHeight(75);
                sinLabel.setAlignment(Pos.CENTER);
                sinLabel.setStyle("-fx-font-size: 15px; -fx-text-fill: white;");
                cosLabel.setText("Kosinus : " + String.format("%.2f", cos));
                cosLabel.setBackground(background);
                cosLabel.setPrefWidth(150);
                cosLabel.setPrefHeight(75);
                cosLabel.setAlignment(Pos.CENTER);
                cosLabel.setStyle("-fx-font-size: 15px; -fx-text-fill: white;");
                tanLabel.setText("Tangen  : " + String.format("%.2f", tan));
                tanLabel.setBackground(background);
                tanLabel.setPrefWidth(150);
                tanLabel.setPrefHeight(75);
                tanLabel.setAlignment(Pos.CENTER);
                tanLabel.setStyle("-fx-font-size: 15px; -fx-text-fill: white;");

            } catch (NumberFormatException e) {
                sinLabel.setText("Masukkan angka yang valid");
                cosLabel.setText("Masukkan angka yang valid");
                tanLabel.setText("Masukkan angka yang valid");
            }
        });
        Button backhome = new Button("Back to Menu");
        backhome.setOnAction(action -> secondScene());

        VBox vbox = new VBox(10, gino, inputTextField, hitungbutton, sinLabel, cosLabel, tanLabel, backhome);
        vbox.setAlignment(Pos.CENTER);
        vbox.setStyle("-fx-background-color: #00BFFF;");

        Scene scene3 = new Scene(vbox, 600, 600);
        stage.setScene(scene3);
    }

 
    public static void main(String[] args) {
        launch(args);
    }
}
