/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package calculator;

import javafx.application.Application;
import javafx.geometry.Pos;
import javafx.geometry.Insets;
import javafx.scene.Group;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.control.TextField;
import javafx.scene.layout.StackPane;
import javafx.scene.layout.HBox;
import javafx.scene.layout.VBox;
import javafx.scene.paint.Color;
import javafx.scene.text.Font;
import javafx.scene.text.Text;
import javafx.stage.Stage;
import javafx.scene.image.Image;
import javafx.scene.image.ImageView;

public class App extends Application {
    Stage mainStage;

    public static void main(String[] args) {
        System.out.println("Launching...");
        launch(args);
    }

    @Override
    public void start(Stage primaryStage) throws Exception {
        
        mainStage= primaryStage;
        mainStage.setTitle("Aplikasi Ganti Nama");

        tampilkanScene1();

        mainStage.show();
    }

    // public void tampilkanScene2(){
    //     Button button = new Button("Pindah Page");
    //     button.setOnAction(action -> {
    //         tampilkanScene1();
    //     });
    //     Scene scene = new Scene(button, 400, 600);
    //     // scene.getStylesheets().add(getClass().getResource("/styles/styleApp.css").toExternalForm());

    //     mainStage.setScene(scene);
    // }


    public void tampilkanScene1(){
        Label text = new Label("Calculator");
        text.setStyle("-fx-font-size:30px; -fx-font-weight:bold;-fx-font-family:arial;-fx-text-fill:white;");

        Image linkLogo = new Image(getClass().getResource("/images/calculator.png").toString(),150,150,false,false);
        ImageView logo = new ImageView(linkLogo);
        
        Button button = new Button("Mulai");
        button.setStyle("-fx-font-size:20px; -fx-font-weight:bold;-fx-background-color: orange; -fx-text-fill: white;-fx-border-radius:100px;-fx-pref-width: 150px; -fx-pref-height: 50px;");
        button.setOnAction(action -> {
            tampilkanScene2();
        });
        
        StackPane stackPane = new StackPane();
        stackPane.getChildren().add(logo);

        VBox group1 = new VBox();
        group1.getChildren().addAll(stackPane, text, button);
        group1.setSpacing(20);
        group1.setAlignment(Pos.CENTER); // Mengatur posisi konten di tengah

        Scene scene = new Scene(group1, 400, 600);
        scene.getRoot().setStyle("-fx-background-color: black;");
        // scene.getStylesheets().add(getClass().getResource("/styles/styleApp.css").toExternalForm());

        mainStage.setScene(scene);
    }

    public void tampilkanScene2(){
        Label text = new Label("Pilih Menu");
        text.setStyle("-fx-font-size:30px; -fx-font-weight:bold;-fx-font-family:arial;-fx-text-fill:white;-fx-margin-top:20px");

        
        Button button1 = new Button("Penjumalahan");
        button1.setStyle("-fx-font-size:20px; -fx-font-weight:bold;-fx-background-color: gray; -fx-text-fill: black;-fx-border-radius:100px;-fx-pref-width: 300px; -fx-pref-height: 50px;");
        button1.setOnAction(action -> {
            tampilkanScene3();
        });

        Button button2 = new Button("Konversi Suhu");
        button2.setStyle("-fx-font-size:20px; -fx-font-weight:bold;-fx-background-color: gray; -fx-text-fill: black;-fx-border-radius:100px;-fx-pref-width: 300px; -fx-pref-height: 50px;");
        button2.setOnAction(action -> {
            tampilkanScene4();
    });
        
        // StackPane stackPane = new StackPane();
        // stackPane.getChildren().add(logo);

        VBox group1 = new VBox();
        group1.getChildren().addAll(text, button1,button2);
        group1.setMargin(text,new Insets(20));
        group1.setSpacing(20);
        group1.setAlignment(Pos.TOP_CENTER);

        Scene scene = new Scene(group1, 400, 600);
        scene.getRoot().setStyle("-fx-background-color: black;");
        // scene.getStylesheets().add(getClass().getResource("/styles/styleApp.css").toExternalForm());

        mainStage.setScene(scene);
    }

    public void tampilkanScene3(){
        Label text = new Label("Jenis Kalkulator");
        text.setStyle("-fx-font-size:30px; -fx-font-weight:bold;-fx-font-family:arial;-fx-text-fill:white;-fx-margin-top:20px");

        TextField field1 = new TextField();
        field1.setStyle("-fx-font-size:20px;-fx-pref-width: 250px; -fx-pref-height: 50px;");

        TextField field2 = new TextField();
        field2.setStyle("-fx-font-size:20px;-fx-pref-width: 250px; -fx-pref-height: 50px;");

        Button b = new Button("calculate");
        b.setStyle("-fx-font-size:20px; -fx-font-weight:bold; -fx-background-color: orange; -fx-text-fill: white; -fx-border-radius: 50px; -fx-pref-width: 300px; -fx-pref-height: 50px;");

        Button c = new Button("clear");
        c.setStyle("-fx-font-size:20px; -fx-font-weight:bold; -fx-background-color: gray; -fx-text-fill: white; -fx-border-radius: 50px; -fx-pref-width: 100px; -fx-pref-height: 50px;");

        Button back = new Button("Back To Home");
        back.setStyle("-fx-font-size:20px; -fx-font-weight:bold;-fx-background-color: black; -fx-text-fill: white;-fx-border-radius:100px;-fx-border-color:white;-px-padding:50px;-fx-pref-width: 400px; -fx-pref-height: 50px;");
        
        Label hasil = new Label("Hasil");
        hasil.setStyle("-fx-font-size:20px;-fx-text-fill: white; -fx-font-weight:bold;");
        
        Label res = new Label("");
        res.setStyle("-fx-font-size:20px;-fx-text-fill: white;");

        back.setOnAction(e->{
            tampilkanScene2();
        });
        c.setOnAction(e->{
            field1.setText("");
            field2.setText("");
            res.setText("");
        });
        b.setOnAction(e -> {

            try {
                int tf1 = Integer.parseInt(field1.getText());
                // System.out.println(tf1);
                int tf2 = Integer.parseInt(field2.getText());
                // System.out.println(tf2);
                int r = tf1 + tf2;
                res.setText(Integer.toString(r));

            } catch (Exception a) {
                res.setText("Invalid Inputs");
            }
        });

        VBox hasilVBox = new VBox(hasil);
        VBox resVBox = new VBox(res);

        hasilVBox.setAlignment(Pos.CENTER_LEFT);
        resVBox.setAlignment(Pos.CENTER_LEFT);

        HBox hbox = new HBox(10);
        hbox.getChildren().addAll(c, b);

        VBox vbox = new VBox(20);
        vbox.getChildren().addAll(text, field1, field2, hasilVBox, resVBox, hbox, back);
        vbox.setAlignment(Pos.TOP_CENTER);
        vbox.setPadding(new Insets(20));


        Scene scene = new Scene(vbox, 400, 600);

        scene.getRoot().setStyle("-fx-background-color: black;");

        mainStage.setScene(scene);

    }

    public void tampilkanScene4(){
        Label text = new Label("Konversi Celcius ke Fahrenhait");
        text.setStyle("-fx-font-size:15px; -fx-font-weight:bold;-fx-font-family:arial;-fx-text-fill:white;-fx-margin-top:20px");

        TextField field1 = new TextField();
        field1.setStyle("-fx-font-size:20px;-fx-pref-width: 250px; -fx-pref-height: 50px;");

        Button b = new Button("calculate");
        b.setStyle("-fx-font-size:20px; -fx-font-weight:bold; -fx-background-color: orange; -fx-text-fill: white; -fx-border-radius: 50px; -fx-pref-width: 300px; -fx-pref-height: 50px;");

        Button c = new Button("clear");
        c.setStyle("-fx-font-size:20px; -fx-font-weight:bold; -fx-background-color: gray; -fx-text-fill: white; -fx-border-radius: 50px; -fx-pref-width: 100px; -fx-pref-height: 50px;");

        Button back = new Button("Back To Home");
        back.setStyle("-fx-font-size:20px; -fx-font-weight:bold;-fx-background-color: black; -fx-text-fill: white;-fx-border-radius:100px;-fx-border-color:white;-px-padding:50px;-fx-pref-width: 400px; -fx-pref-height: 50px;");
        
        Label hasil = new Label("Konversi");
        hasil.setStyle("-fx-font-size:20px;-fx-text-fill: white; -fx-font-weight:bold;");
        
        Label res = new Label("");
        res.setStyle("-fx-font-size:20px;-fx-text-fill: white;");

        back.setOnAction(e->{
            tampilkanScene2();
        });
        c.setOnAction(e->{
            field1.setText("");
            res.setText("");
        });
        b.setOnAction(e -> {

            try {
                int tf1 = Integer.parseInt(field1.getText());
                // System.out.println(tf1);
                // System.out.println(tf2);
                int r = (tf1 *  9/5) + 32;
                res.setText(Integer.toString(r));

            } catch (Exception a) {
                res.setText("Invalid Inputs");
            }
        });

        VBox hasilVBox = new VBox(hasil);
        VBox resVBox = new VBox(res);

        hasilVBox.setAlignment(Pos.CENTER_LEFT);
        resVBox.setAlignment(Pos.CENTER_LEFT);

        HBox hbox = new HBox(10);
        hbox.getChildren().addAll(c, b);

        VBox vbox = new VBox(20);
        vbox.getChildren().addAll(text, field1, hasilVBox, resVBox, hbox, back);
        vbox.setAlignment(Pos.TOP_CENTER);
        vbox.setPadding(new Insets(20));


        Scene scene = new Scene(vbox, 400, 600);

        scene.getRoot().setStyle("-fx-background-color: black;");

        mainStage.setScene(scene);

    }
}